#ifndef EDGEOTA_BOOTLOADER_PROTOCOL_H
#define EDGEOTA_BOOTLOADER_PROTOCOL_H

#include <stdint.h>

enum {
    BL_UP_BOOT_HELLO = 0x20,
    BL_UP_VERSION_REPORT = 0x21,
    BL_UP_OTA_ACK = 0x22,
    BL_UP_OTA_NACK = 0x23,
    BL_UP_OTA_PROGRESS = 0x24,
    BL_UP_BOOT_REPORT = 0x25,
    BL_UP_APP_CONFIRM = 0x26,
    BL_UP_CRASH_REPORT = 0x27,

    BL_DN_OTA_QUERY = 0x30,
    BL_DN_OTA_PREPARE = 0x31,
    BL_DN_OTA_DATA = 0x32,
    BL_DN_OTA_VERIFY = 0x33,
    BL_DN_OTA_COMMIT = 0x34,
    BL_DN_OTA_ABORT = 0x35,
    BL_DN_REBOOT_TO_BOOTLOADER = 0x36,
    BL_DN_GET_VERSION = 0x37
};

#endif
